// SPDX-License-Identifier: CC-BY-4.0

= RISC-V Watchdog Timer Specification
:author: RISC-V Platform Specification Task Group
:email: tech-unixplatformspec@lists.riscv.org
:revnumber: 1.0-draft-0.3
:sectnums:
:xrefstyle: short
:toc: macro

// Table of contents
toc::[]

[preface]
== Copyright and license information

This RISC-V watchdog timer specification has been contributed directly or
indirectly by:

[%hardbreaks]
* Greg Favor <gfavor@ventanamicro.com>
* Kumar Sankaran <ksankaran@ventanamicro.com>
* Anup Patel <anup.patel@wdc.com>

*NOTE:* Please add yourself to the above list if you have contributed to
the RISC-V watchdog timer specification.

It is licensed under the Creative Commons Attribution 4.0 International
License (CC-BY 4.0). The full license text is available at
https://creativecommons.org/licenses/by/4.0/.

[preface]
== Change Log

=== Version 1.0

* Initial release with a simple two-stage watchdog device

== Watchdog Timer

The watchdog timer device provides a simple two-stage timer controlled
through one 32-bit memory-mapped control and status register (*WDCSR*).

The basic function is to wait a software-configured period of time - with
the expectation that system software will re-initialize the watchdog state
within this period of time. If this time period elapses without software
re-init occurring, then a first-stage timeout register bit (*S1WTO*) is set
within WDCSR that asserts an interrupt request output signal to notify the
system of a stage 1 watchdog timeout. If a second period of time elapses
without software re-init of the watchdog, then a second-stage timeout
register bit (*S2WTO*) is set within `WDCSR` that generates a separate
interrupt request output signal to notify the system of a stage 2 watchdog
timeout.

Normally system software will periodically re-init the watchdog state by
writing WDCSR with S1WTO=S2WTO=0 more frequently than the configured timeout
time period.

=== Timeout Counter

A system's MTIME real-time counter provides the timebase or "clock tick" for
the watchdog timeout period. The timeout period itself - in units of watchdog
clock tick - is specified by a *10-bit WTOCNT* field of WDCSR. When WDCSR is
written, the WTOCNT value initializes a 10-bit down counter (aka timeout
counter) that decrements with each watchdog tick.

The watchdog tick occurs when the time value in the MTIME register advances
and a selected bit of MTIME transitions from 0 to 1. If the MTIME resolution
is `M` seconds, the MTIME bit position for watchdog tick is `B` and WTOCNT
value is `N` then watchdog tick resolution is `Mx2^(B+1)^` seconds and
watchdog timeout period is `NxMx2^(B+1)^` seconds. This means use of a
different MTIME resolution and a different MTIME bit results in a different
watchdog tick resolution.

[sidebar]
--
[underline]*_Example1:_* +
A 10 ns unit of resolution for MTIME values (corresponding to a 100 MHz rate
of increments), selection of MTIME bit 24 results in watchdog tick resolution
of 0.3355 seconds and a maximum timeout period (WTOCNT=0x3FF) of 343+ seconds.
--

[sidebar]
--
[underline]*_Example2:_* +
A 100 ns unit of resolution for MTIME values (corresponding to a 10 MHz rate
of increments), selection of MTIME bit 20 results in watchog tick resolution
of 0.2097 seconds and a maximum timeout period (WTOCNT=0x3FF) of 214+ seconds.
--

The choice of MTIME resolution and MTIME bit position for watchdog tick is
platform specific and these parameters should be discoverable by software
via platform-specific means. It is recommended that these parameters are
chosen so as to provide a watchdog tick resolution between 0.1 sec and 1 sec,
ensuring a maximum timeout period (WTOCNT=0x3FF) greater than 100 seconds.

=== WDCSR Register

The WDCSR is a 32-bit little-endian memory mapped register at offest 0x0 of
the watchdog timer device. Various fields of the WDCSR are shown in the
<<table_wdcsr_register_fields>> below.

[#table_wdcsr_register_fields]
.Watchdog Control and Status Register
[cols="1,1,3", width=80%, align="center", options="header"]
|===
| Field      | Bits | Description
| WDEN       | 0:0  | Enable the watchdog timer
| *RESERVED* | 1:1  | Reserved for future use
| S1WTO      | 2:2  | Stage1 watchdog timeout
| S2WTO      | 3:3  | Stage2 watchdog timeout
| WTOCNT     | 13:4 | Watchdog timeout count
| *RESERVED* | 31:9 | Reserved for future use
|===

WDEN, when set, enables the watchdog timer device. When clear, the watchdog
is disabled and the S1WTO and S2WTO output signals are forced to be zero
(deasserted).

Software should initialize (and periodically re-initialize) WDCSR by writing
WDEN=1, S1WTO=S2WTO=0, and WTOCNT with the desired timeout period. The 10-bit
WTOCNT value initializes a 10-bit timeout counter. The following state
transitions occurs upon every watchdog tick when WDEN=1:

. If timeout counter is non-zero then
.. Decrement timeout counter
. else
.. If S1WTO=1 then
... Set S2WTO
.. else
... Set S1WTO and re-initialize the timeout counter with WTOCNT

[sidebar]
--
[underline]*_Note:_* +
The first watchdog tick that occurs after a WDCSR write may represent just
a fraction of a full tick period. It is expected that (WTOCNT >= 2) values
will be used so as to ensure one or more full tick periods occur before the
timeout counter reaches zero.
--

When S1WTO is set and while it remains set, a stage 1 watchdog timeout output
signal from the watchdog device is asserted.  Similarly, when S2WTO is set
and while it remains set, a stage 2 watchdog timeout output signal from the
watchdog device is asserted.

System reset should disable the watchdog by setting WDEN=0.
